a = input('Digite algo:  ')
print('O Tipo primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('É um numero?', a.isnumeric())
print('é alfabetico? ', a.isalpha())
print(' É alfanumerico?', a.isalnum())
print('Esta em Maisculas?', a.islower())
print('Esta capitalizada?', a.istitle())
